`protect
`define BUG1DONEANDDUSTEDWITH
`define BUG2DONEANDDUSTEDWITH
`define BUG3DONEANDDUSTEDWITH
`define BUG4DONEANDDUSTEDWITH
`define BUG5DONEANDDUSTEDWITH

`define BUG6DONEANDDUSTEDWITH
`define BUG7DONEANDDUSTEDWITH
`define BUG83DONEANDDUSTEDWITH
`define BUG9DONEANDDUSTEDWITH
`define BUG10DONEANDDUSTEDWITH

`define BUG11DONEANDDUSTEDWITH
`define BUG12DONEANDDUSTEDWITH
`define BUG13DONEANDDUSTEDWITH
`define BUG14DONEANDDUSTEDWITH
`define BUG15DONEANDDUSTEDWITH

`define BUG16DONEANDDUSTEDWITH
`define BUG17DONEANDDUSTEDWITH
`define BUG183DONEANDDUSTEDWITH
`define BUG19DONEANDDUSTEDWITH
`define BUG20DONEANDDUSTEDWITH

`define BUG21DONEANDDUSTEDWITH
`define BUG22DONEANDDUSTEDWITH
`define BUG23DONEANDDUSTEDWITH
`define BUG24DONEANDDUSTEDWITH
`define BUG25DONEANDDUSTEDWITH

`define BUG26DONEANDDUSTEDWITH
`define BUG27DONEANDDUSTEDWITH
`define BUG283DONEANDDUSTEDWITH
`define BUG29DONEANDDUSTEDWITH
`define BUG30DONEANDDUSTEDWITH


`define BUG31DONEANDDUSTEDWITH
`define BUG32DONEANDDUSTEDWITH
`define BUG33DONEANDDUSTEDWITH
`define BUG34DONEANDDUSTEDWITH
`define BUG35DONEANDDUSTEDWITH

`define BUG36DONEANDDUSTEDWITH
`define BUG37DONEANDDUSTEDWITH
`define BUG383DONEANDDUSTEDWITH
`define BUG39DONEANDDUSTEDWITH
`define BUG40DONEANDDUSTEDWITH

`define BUG41DONEANDDUSTEDWITH
`define BUG42DONEANDDUSTEDWITH
`define BUG43DONEANDDUSTEDWITH
`define BUG44DONEANDDUSTEDWITH
`define BUG45DONEANDDUSTEDWITH

`define BUG46DONEANDDUSTEDWITH
`define BUG47DONEANDDUSTEDWITH


//`define DEBUG
	
`endprotect
